%%{init: {'securityLevel': 'loose', 'theme':'base'}}%%    
classDiagram
direction TB
class _ { << mermaid.xqm >>}


link _ "modules/F000001/index.html" "This is a tooltip for quodatum:xqdoca.generator.mermaid" 

